Prefixable Keys for env and flag Loaders
pcelvng/go-config pull request #40
Opened 2022-06-02 18:06 UTC by Jmoore1127

2022-06-03 17:48 UTC, rlball requested changes

2022-06-03 17:48 UTC, rlball commented on config.go
> +		prefix = util.ToLowerSnake(prefix)
Why would this always be lower snake case? Doesn't it get formatted later in the respective flag and env loader?

2022-06-03 17:48 UTC, rlball commented on load/flag/load.go
> +	"github.com/pcelvng/go-config/util"
do you mind running go imports on this?

2022-06-06 20:18 UTC, Jmoore1127 commented on config.go
> +		prefix = util.ToLowerSnake(prefix)
This was mostly to give a sane starting point. I wanted to avoid unexpected characters like spaces, periods, etc. Individual loaders provide their own transforms as well (e.g. flag to lower kebab and env to screaming snake case).

2022-06-06 20:18 UTC, Jmoore1127 commented on load/flag/load.go
> +	"github.com/pcelvng/go-config/util"
:+1:

2022-06-07 18:22 UTC, rlball approved these changes

2022-06-07 19:05 UTC, rlball approved these changes

2022-06-07 19:05 UTC, merged